### ISSUE TITLE
Dates are wrong and previous dates not showing up

### ISSUE THREAD

**Issue by dhayams** [aprildunnam/PowerApps#10]

**Comment by dhayams** [comment]
![Weeklist](https://user-images.githubusercontent.com/47501013/101189116-a1016580-367c-11eb-9c6b-03bfb2708abe.PNG)
![Wrong Dates](https://user-images.githubusercontent.com/47501013/101189125-a2cb2900-367c-11eb-9535-7306fb3e2967.PNG)

**Comment by aprildunnam** [comment]
Please make sure you're using the most recent version of the app stored here: https://github.com/pnp/powerapps-samples/tree/main/samples/Timesheet
