### ISSUE TITLE
Can't book more than one time slot per day

### ISSUE THREAD

**Issue by mausiku** [aprildunnam/PowerApps#103]
Hi April, 
The Desk booking app is great, however, I am unable to book different time slots for a desk per day. Once I book e.g 10am - 11am, then that desk is no longer appearing even if I pick 2pm - 3pm on the same date. It will be only available if I pick a different date.

**To Reproduce**
1. Go to new booking
2. Click on When to choose Date
3. Choose time slot and click continue
4. Select Desk
5. See error (Desk does not appear)

**Expected behavior**
The desk should still appear under Select a Desk screen as there are time slots not booked yet.

**Desktop **
 - OS: [Windows 11]
 - Browser [Edge]
 - Version [110.0.1587.41]

**Comment by RandallMoraAlfaro** [comment]
hello! same issue here, if you find put something let me know, thanks!

**Comment by mausiku** [comment]
> hello! same issue here, if you find out something let me know, thanks!

Hi, I managed to get it working. It was simply the Date & Time Format setting. When in SharePoint "Desk Reservations" list, go to Settings in the top right corner and choose List settings. Under Columns, click on the "Check Out From" column. Under Date and Time Format, choose "Date and Time" instead of "Date Only". Do the same for the "Check Out To" column.
