### ISSUE TITLE
Desk not available in hourly reservations

### ISSUE THREAD

**Issue by Drastaa** [aprildunnam/PowerApps#108]
Hi,

I'm running the latest version of the app. When creating a booking - if someone creates hourly reservation (let's say from 7:00-12:00), this desk becomes unavailable for anyone else trying to book from 12:30-17:00.

The code is: (Nadpis = Title)
`Filter(Sort(col_Desks;Nadpis);Not(Nadpis in col_Reservations.DeskText) && Active = 1 && Or(DeskSearchFilter.Text in Nadpis ; DeskSearchFilter.Text in Description))`

I can see that if I select the time frame outside of the initial reservation, the col_Reservations shows the desk and therefore because of the `Not(Nadpis in col_Reservations.DeskText)` this desk is not shown for selection.

Any inputs are appreciated as I don't understand working with collections at all.

Thank you :)

**Comment by A-Kurtay** [comment]
Hi April, I had placed the same question also in your youtube channel. Can you help solving this issue? 
Thank you

**Comment by Drastaa** [comment]
> Hi April, I had placed the same question also in your youtube channel. Can you help solving this issue? Thank you
> 
> Been searching the fix few weeks, thanks to Mausiku in issue 105, this issue is fixed.
> 
> _It is the Date & Time Format setting. When in SharePoint "Desk Reservations" list, go to Settings in the top right corner and choose List settings. Under Columns, click on the "Check Out From" column. Under Date and Time Format, **choose "Date and Time" instead of "Date Only".** Do the same for the "Check Out To" column._

Wow, okay, the column was setup as Date and Time but in the settings, there was "Date only" exactly as you've desribed. Thank you so much!
