### ISSUE TITLE
Reservation Importer flow fails

### ISSUE THREAD

**Issue by Remmy-OSI** [aprildunnam/PowerApps#11]
The reservation importer flow is failing to add the columns to the default view (not sure if this causes a problem) but the cause is that when creating the new fields for "check out to", "check out from" and "reserved by" you've not put spaces in.

This causes initially the flow to fail (as the "add a field to default view 2" action uses spaces) and also the app not to work.

Suggested update is to change the field adding actions to include spaces.

Once I worked this out, the app works great! Would be good to get a tablet layout version as well, but might take the time to create this myself.

**Comment by mwermeester** [comment]
Thanks! This indeed fixes the issue. 

Also, I had to add spaces for the "check out from" field.
