### ISSUE TITLE
Data not loading on powerapps

### ISSUE THREAD

**Issue by sainikhilab** [aprildunnam/PowerApps#13]
Initially I got errors for the column names (Check out from etc.) and maplinkl, after fixing these issues and removing all the errors I am able to run the app and book a desk but the data doesn't show up on the dashboard/ my appointments section. However the reservation is reflecting on the SharePoint site.

**Comment by itl-defilipg** [comment]
I have insert a new timesheet record but on the tab "My TimeSheets" the page are empty. Help me please...

**Comment by Danish-Izani** [comment]
> Initially I got errors for the column names (Check out from etc.) and maplinkl, after fixing these issues and removing all the errors I am able to run the app and book a desk but the data doesn't show up on the dashboard/ my appointments section. However the reservation is reflecting on the SharePoint site.

@sainikhilab Have you solve your issue on the Dashboard? If yes, can you teach me on how to solve it because I encounter the same issue where the booking will appear on Sharepoint but the data doesn't show up on Dasboard?

**Comment by aprildunnam** [comment]
Please try the latest version of the app which should resolve most issues: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip
