### ISSUE TITLE
Cannot Import Solution in Flow/Power Automate

### ISSUE THREAD

**Issue by ITAHIR1982** [aprildunnam/PowerApps#14]
any update? I am getting the same error.

_Originally posted by @ITAHIR1982 in https://github.com/aprildunnam/PowerApps/issues/9#issuecomment-759771265_

**Comment by ITAHIR1982** [comment]
when I tried to import the solution in the MS Flow, it gave me an error " 
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported"

**Comment by PeteWelsh** [comment]
Hi, when importing the provisioner flow from My flows, I get the message "Something went wrong. Please try again later." I've tried for days without success.

**Comment by Stuartnt** [comment]
HI April,

I have imported the Template Provisioner file into Power Automate and this ran as expected. I have accessed the flow and updated the section to insert my SP URL as per the instructions. Saved the Flow and when running it I get the following error and cannot set up the lists as a result.
Could you tell me is this is an issue with the import / flow or I am Missing something permissions wise. I am the site owner and have full control, so not sure it is a permissions issue. 

Thanks

Stuart

<img width="796" alt="image" src="https://user-images.githubusercontent.com/95724470/148389074-1811406b-31a4-4b05-8605-b9654cbed7d4.png">

**Comment by aprildunnam** [comment]
I have moved away from the flow to provision in favor or documenting the instructions on how to setup the list.  The updated instructions and app are available here: https://github.com/pnp/powerapps-samples/tree/main/samples/Timesheet
