### ISSUE TITLE
Timesheet Issues

### ISSUE THREAD

**Issue by JShipma6281** [aprildunnam/PowerApps#15]
I have followed the deployment directions, but have several errors.  Attached is an example of the type of error I am getting.  I would appreciate any help you could give me.  Thank you.
<img width="1356" alt="Untitled" src="https://user-images.githubusercontent.com/78827418/107437541-c6837300-6af4-11eb-90b8-ced35e8b5028.png">

**Comment by ken-pina-inclusa** [comment]
Agree. This app doesn't work out of the box. The steps are pretty clear, provisioning flow works, but the resulting app install (using V2 download) and the SharePoint lists don't seem to be aligned which is creating over 100 errors in the app checker. Probably can go through and resolve them, but it's not functional purely by following the steps in the .md.

**Comment by unifiedesystems** [comment]
Me too. I removed the connections, but somehow they keep getting referenced AND re-added. Only form that I got half working is New entry.

**Comment by ken-pina-inclusa** [comment]
Make sure you only run the provisioning flow portion once. After that's done and you can see that the lists are created in SharePoint, you can delete that flow from your environment.

I deleted everything and ran it all again and got a different result on the fourth attempt.

This time there were only a couple of errors in the app, all which were resolved by changing this piece of code from "Week Start" to "Week_x0020_Start.

![image](https://user-images.githubusercontent.com/82233903/114388911-f0d7c800-9b59-11eb-9d1e-247ea47475b8.png)

Everything is up and running now.

**Comment by AleElf** [comment]
@ken-pina-incluse; that also solved my issue.

**Comment by aprildunnam** [comment]
Please make sure you're using the most recent version of the app stored here: https://github.com/pnp/powerapps-samples/tree/main/samples/Timesheet
