### ISSUE TITLE
Required Training App

### ISSUE THREAD

**Issue by AnnetteMa** [aprildunnam/PowerApps#16]
Not able to assign trainings to staff. On the Training Details screen the Assign button (button1) has an error that 'AssignedTo' does not exist.

**Comment by aprildunnam** [comment]
You'll have to compare the fields in your SharePoint list with the Power App. Double check that you have a Person or group field called "AssignedTo" in your SharePoint list.  These fields are case sensitive and spaces matter. I believe the app is looking for a column with no spaces in the name
