### ISSUE TITLE
Change the approver on Timesheets

### ISSUE THREAD

**Issue by jchassehb** [aprildunnam/PowerApps#17]
After a few attempts, I was not able to adjust the approver for the time sheet app to the actual manager of the employee. Any guidance on how to do this?

**Comment by nems86** [comment]
Same issue here , did you find a solution ?

**Comment by jchassehb** [comment]
No solution found yet

**Comment by nems86** [comment]
i found one yesterday !! 

 Manager: {
                '@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedUser",
                Claims: "i:0#.f|membership|" & Office365Users.ManagerV2(User().Email).mail,
                Department: "",
                DisplayName: "",
                Email: Office365Users.ManagerV2(User().Email).mail,
                JobTitle: "",
                Picture: ""

**Comment by jchassehb** [comment]
Where are you pulling the managers list from?

**Comment by nems86** [comment]
contact me @ FB messenger i can explain for you @ abdalla elnahas

**Comment by nems86** [comment]
![Untitled](https://user-images.githubusercontent.com/63870284/111894884-9ac2a980-8a1f-11eb-9c2e-78d477549246.png)

**Comment by jchassehb** [comment]
I'm not able to find your profile on FB Messenger, can you send me a link your profile and I will message you?

**Comment by nems86** [comment]
+966500572254 / whatsapp

**Comment by aprildunnam** [comment]
You can use the Office365Users connector to get the manager:
 
 Office365Users.ManagerV2(User().Email).mail
