### ISSUE TITLE
Desk Reservation Provisioner failing to add created fields to the default view 2 (very last step)

### ISSUE THREAD

**Issue by pasteiner** [aprildunnam/PowerApps#19]
Hi April,

Really hoping to use this app soon, looks great, and your video is great as well.  I'm having a problem getting the flow to create the tables for me, it keeps failing on the last step and only creates the Title and DeskText in the Desk Reservations table.  Is there a bug in the flow, or is it just me?

**Comment by fiedback** [comment]
Similar to me. Get the not:
"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported." @aprildunnam can you please help. Looking forward to your App.

**Comment by steinhenge** [comment]
Thank you April,

I was able to build the table manually and get it working.  It is a nice app, and your video is great as well.  I did notice that the link for this app took me to the lost and found app on github.  I was able to navigate up a level and find the app but just thought you might like to know.

Cheers!

Patrick Steiner
Programmer/Analyst
540-441-8913
703-431-2202 (mobile)
[PHC.Edu]<http://www.phc.edu/>
[Instagram]<https://www.instagram.com/patrickhenrycollege/>
[Share on Facebook]<https://www.facebook.com/patrick.henry.college/?fref=ts>
[Share on LinkedIn]<https://www.linkedin.com/company/235881?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A235881%2Cidx%3A2-1-6%2CtarId%3A1458139029888%2Ctas%3APatrick%20Henr>
[Share on Twitter]<https://twitter.com/patrickhenrycol>
[Share on Pinterest]<https://www.pinterest.com/patrickhenrycol>

**Comment by fiedback** [comment]
@steinhenge: Could you please help me with the list? I get the first ("Desks")= List but than it fails. And I could not manage to make the lists on my own.

**Comment by steinhenge** [comment]
![desks](https://user-images.githubusercontent.com/36079069/113166142-7c735f80-9210-11eb-898b-7ea70ea260fd.png)
![reservations](https://user-images.githubusercontent.com/36079069/113166155-7ed5b980-9210-11eb-831a-a3e5297b4a1b.png)
please find the layout of the sharepoint tables.   I looked up the content type values to determine what the columns should be.  Hope this helps.

**Comment by steinhenge** [comment]
There might be an extra maplink column in the desks tables...just noticed that.

**Comment by fiedback** [comment]
@steinhenge Thanks. Will try it asap. ;-)

**Comment by aprildunnam** [comment]
I have sense abandoned the provisioner approach and opted to document the list configuration instead.  Please see the ReadMe here for how to setup the underlying lists:
Please try the latest version of the app which should resolve most issues: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/
