### ISSUE TITLE
Sharepoint site Language and spaces in columns

### ISSUE THREAD

**Issue by azi252** [aprildunnam/PowerApps#2]
Hi,

sharepointsite language must be english. The Flow is not working for sites in german / other languages :-) 
Maybe you can add this to your readme-file?

Best regards
Alex

**Comment by amannall** [comment]
The columns in the creator bit have no spaces but the app has spaces so you ahve to go and correct all of those.

Also the flow itself when creating the last view has spaces in the column names but the actual column names don't have spaces.

Additionally the my bookings and appointments bit doesn't seem to pull info.

How is the Active column in the Desks list used - it would be good to be able to filter on desks where active = 1 or 0 (so available or not available).

**Comment by drakinor** [comment]
Hi,

For some reason I cannot get the "confirm" button to work in my environment. The app gets to the confirmation and the title is missing and confirm is clickable but no actual action appears to take place and it never hits the success page or writes to sharepoint. Not sure what I am doing wrong.

**Comment by aprildunnam** [comment]
I have removed the version which used a Flow to create the lists.  For simplicity I have opted to include the SharePoint list configuration in the documentation instead as seen in the most recent version of the template: https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation
