### ISSUE TITLE
Booking PowerApps Not pulling data from the lists

### ISSUE THREAD

**Issue by ITInfinityAU** [aprildunnam/PowerApps#24]
Hi All, I am a newbie to power apps. Trying to use the @aprildunnam booking app. Followed her instructions, but I am getting errors when it's trying to pull data from the 2 x lists. Its says 'Name isn't valid. This Identifier isn't recognized'.

Any help would be greatly appreciated. 
![powerapps](https://user-images.githubusercontent.com/85603380/121298939-0558f680-c938-11eb-967b-3a5d0776fa58.png)

**Comment by PowerAppsGC** [comment]
I had this issue.  I needed to change filter to the following in a couple of places.  Its been well commented on so this was not of my own doing so not claiming to be.

'Reserved By'.DisplayName = currentUser.FullName && 'Check Out From' >= Today()

**Comment by Steviegreen7** [comment]
@ITInfinityAU did you manage to resolve this, I have tried the update from @PowerAppsGC but am struggling to find the heavily commented resolution! Thanks

**Comment by nguyenhuu12345** [comment]
i have the same issue, can anyone help to resolve it?

**Comment by aprildunnam** [comment]
If the names of your columns in SharePoint don't match up it's going to cause the errors that you're describing.  In the case of the screenshot it looks to be a problem with case.  The field names are case sensitive so it would need to be called DeskName instead of deskname.

**Comment by nguyenhuu12345** [comment]
Hi @aprildunnam ,
Thanks for your App, during export your template to my App, it not work properly: 
  
![image](https://user-images.githubusercontent.com/59440390/132531935-56e56d07-a989-4b23-a568-52f7a1454880.png)
![image](https://user-images.githubusercontent.com/59440390/132532027-3a4fcf1f-e040-4a84-9ef9-6344facdb77d.png)
![image](https://user-images.githubusercontent.com/59440390/132532168-f05c4044-cd97-41c3-b51d-4c1a4c21f953.png)
Desk list:
![image](https://user-images.githubusercontent.com/59440390/132532390-e0498a9c-f720-4975-b217-3ebaf73b6b1b.png)
Desk Reservation:
![image](https://user-images.githubusercontent.com/59440390/132532611-b3f4a2b5-22d8-4ef5-b71a-13b31701105d.png)
Flow:
![image](https://user-images.githubusercontent.com/59440390/132532742-fb01311a-3297-4300-9afc-5ccdb53a4956.png)

Do i miss something? Would you please give me suggestion to solve it?

Thank you!

**Comment by Rmaravanyika** [comment]
Is this still a valid issue @aprildunnam believes this has to do with naming of columns. If it's no-longer valid.
