### ISSUE TITLE
Desk Reservation issues with opening the image associated with the Desk

### ISSUE THREAD

**Issue by PowerAppsGC** [aprildunnam/PowerApps#25]
Hi April,

I have the app working pretty well.. Thank you for all the time spent on the development.  I am having an issue when clicking on the small link on the desk booking screen that should pop up the image in that link but all i am seeing is a grey screen.  Just wondered if this is a common issue?  I have checked the column name which is MapLinkl and this is consistant with what i have seen others using.  Also have tried with renaming this column jsut in case i had a typo to MapLink and Map Link but this is not making any difference.  Then i was thinking that it might be the link that is incorrect.  I am currently using a link to an image in the document library where the Desk list resides.
Any pointers gratefully received.

**Comment by PowerAppsGC** [comment]
OK figured it out.  Needed to upload the images to an image library not just a norm document library and then use the link for the original image not the share link.   this is now showing on the app.

**Comment by pmakai** [comment]
@PowerAppsGC : I have the same issue. Could be be a little more specific about which link you used? I've tried to put an image into a image library, and use the link in the MapLinkl field, but I'm still getting the grey screen.

**Comment by PowerAppsGC** [comment]
@pmakai OK so when viewing the image once its been uploaded to SharePoint you see a link in the address bar similar to this
https://SITENAME/hotdesking/DeskImages/Forms/Thumbnails.aspx?id=%2Fhotdesking%2FDeskImages%2FAssembly%20Room%2Epng&parent=%2Fhotdesking%2FDeskImages
I found this gave me a grey screen.  However if you select the option at the top of the screen whch says "View Original" then the link alters to
https://SITENAME/hotdesking/DeskImages/Assembly%20Room.png

then the desks starting appearing within the app for me.

Hope that helps

**Comment by pmakai** [comment]
Great, thanks a million! This really solved everything, and now I have a working map!

**Comment by PowerAppsGC** [comment]
No worries.  All i need now is to set it so that the users cant book 2 desks at the same time..  They cant book the same desk, thats fine but i need to stop them booking Desk 1 and 2 at the same time.

**Comment by pmakai** [comment]
You can toggle how checkboxes are displayed like this: 

https://powerusers.microsoft.com/t5/Building-Power-Apps/Select-single-checkbox-within-a-Gallery/td-p/756528

Once someone checks a box, the rest become inactive/invisible. 

Worked for me. By the way, the app only saves the last desk a user clicked on, so it's not that big of a deal. But for the sake of clarity, toggling is useful.
