### ISSUE TITLE
"New Timesheet" is not working as it is expected

### ISSUE THREAD

**Issue by aaronooiweita** [aprildunnam/PowerApps#26]
Currently the "New Timesheet" remembers the previous hours being inputed. How can I make it so every-time when I go into "New Timesheet", it will be a brand new timesheet without any information being saved from previous inputs?

**Comment by aprildunnam** [comment]
Please make sure you're using the most recent version of the timesheet app stored here: https://github.com/pnp/powerapps-samples/tree/main/samples/Timesheet
