### ISSUE TITLE
Required Training App

### ISSUE THREAD

**Issue by wmedina1991** [aprildunnam/PowerApps#28]
Is there a way to include Microsoft Stream Videos in the galleries? We noticed the galleries only seem to work with YouTube links.

**Comment by dominic-mitchell** [comment]
I don't seem to be able to get any video link to work whether it's Stream (our preferred) or YouTube. 

Has anyone else experienced this issue and have a fix?

**Comment by aprildunnam** [comment]
If you want to use Stream videos instead then you should change the media player in the app to the Stream video player.  More info is found here: https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-stream-video
