### ISSUE TITLE
Duplicate bookings possible

### ISSUE THREAD

**Issue by ConnorWigg** [aprildunnam/PowerApps#30]
If a desk is booked between 9-5 and someone tries to book between 10-6 booking is possible.

**Comment by khennessy74** [comment]
I Solved this by changing the galleryAvailDesk Items property to

`Filter( 
    Desks, 
    Not( 
        Title in Filter( 
            'Desk Reservations', 
            
            'Check Out To' >= DateAdd(startTime, 1, Minutes ) && 'Check Out To' <= endTime || 'Check Out From' <= endTime && 'Check Out To' >= endTime 
        ).DeskText 
    ) && Active = 1 

) `


Changed first 'Check Out From' to 'Check Out to'
Added one minute onto the start time by changing startTime to  DateAdd(startTime, 1, Minutes )

@aprildunnam  can you confirm code is ok please?

**Comment by aprildunnam** [comment]
@khennessy74 - Yes that code is ok. I am currently working on an updated version of the template to address some bugs and will include this fix in the new template.  Thank you!
