### ISSUE TITLE
Time Validation

### ISSUE THREAD

**Issue by firestorm888** [aprildunnam/PowerApps#31]
Hello, can we put a validation that the time To is later than time From?

**Comment by aprildunnam** [comment]
Hi @firestorm888 - can you please let me know which template you are referring to?

**Comment by firestorm888** [comment]
hello April, it's the Seat Booking app.

**Comment by aprildunnam** [comment]
This issue has been addressed in the latest version of the app here: https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation
