### ISSUE TITLE
Desk Reservation files not available 

### ISSUE THREAD

**Issue by jeetsharma78** [aprildunnam/PowerApps#32]
Hi @aprildunnam ,

It's a very good initiative.
Looks like Desk Reservation files not available in the repository.

Could you please help? 

Many Thanks 

Jeet

**Comment by jbeirnemko** [comment]
Hi, you need to create a list called Desk Reservations in a SharePoint site, then 'add data' to link to the list. You need to do the same for Desks.

**Comment by jeetsharma78** [comment]
Thanks @jbeirnemko .
I meant the complete set of this PowerApps package is not available on the link.
Looks like it's removed for some reason.

**Comment by jbeirnemko** [comment]
I downloaded it yesterday. Go to https://github.com/aprildunnam/PowerApps > Code (Green button) > Download Zip > Import to MS Power Automate (MS Flow) not MS Power Apps.

Can you then please try to help me with my 3 questions!! Thanks

**Comment by aprildunnam** [comment]
I temporarily took the sample down because I needed to take some vacation time and I was getting an overwhelming amount of requests for support and/or bug reports on this sample code.

**Comment by jeetsharma78** [comment]
Ok. Vacation Approved 😁 hehe

Thanks for letting us know.

Keep up the fantastic work. It's really inspiring.

**Comment by aprildunnam** [comment]
@jeetsharma78 The MSAPP file for this template is available here: https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation/solution

**Comment by jeetsharma78** [comment]
> @jeetsharma78 The MSAPP file for this template is available here: https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation/solution

Thanks @aprildunnam 
Much Appreciated
