### ISSUE TITLE
Select(Parent);UpdateContext({showMap:!showMap})

### ISSUE THREAD

**Issue by jbeirnemko** [aprildunnam/PowerApps#33]
Hi, I cant get the map to show. I have tried a pdf in a document library and a jpeg in a photo library. What am I missing? What dimensions should the file (pdf or jpeg) be? The rest of the app is working perfect, thanks so much for this btw. Any help would be appreciated. Thanks.

**Comment by aprildunnam** [comment]
@jbeirnemko A jpeg should work.  How are you getting the URL of the image to put in the Desk Reservations Map Link field?  If you use the copy link functionality in SharePoint that won't work.  You need to get the absolute path of the image.  So if you open the image you should see a path like:  https://yoursharepointsite.sharepoint.com/sites/yoursite/yourlibrary/image.png.  That's the URL you need

**Comment by aprildunnam** [comment]
All these image issues should be fixed with the new update. Power Apps now natively supports the new Image field which should fix the issues: https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation
