### ISSUE TITLE
Can't show the picture of office to see the desks on Phone

### ISSUE THREAD

**Issue by nguyenhuu12345** [aprildunnam/PowerApps#37]
Hi @aprildunnam  ,
Thank for your great template, i have the issues need you help:
1. For the picture of desks in the office, i store it in SharePoint document and share to Desk list, that it JPG file but it can't show on the Phone or Tablet devices, it will blur when user click to see the desk. how can i show it?
![image](https://user-images.githubusercontent.com/59440390/132834777-45ffcb59-b9ed-4e59-ba18-d6c439350181.png)

2. How can we select the day like Monday, Wednesday, Friday or Tuesday ,Thursday and just allow for user book only one desk for one day? For current templet, user can book multi days with more than two desk but that the system will note that user use two desk during time they book so another user don't have more desk to book.

Please help to share your solution to fix my issues.
Thanks so much.  
Tomy.

**Comment by SharaMostar** [comment]
I have same issue on the phone

**Comment by ollimenzel** [comment]
I had the same issue, as in our company we are not allowed to download files from SharePoint.
I solved the problem by uploading those files to an Azure Storage (Blob Storage). Now using this link in the SharePoint list is giving me exactly what I need.

**Comment by SharaMostar** [comment]
> I had the same issue, as in our company we are not allowed to download files from SharePoint.
> I solved the problem by uploading those files to an Azure Storage (Blob Storage). Now using this link in the SharePoint list is giving me exactly what I need.

It works :) thank you for advice . Strange that it does not work from sources like Sharepoint :(

**Comment by Sammy990** [comment]
I have the same problem within the PowerApp App on iPhone when using links from SharePoint. Anyone know the technical problem behind this behavior? I can't use Azure Blob Storage and must rely on SharePoint.

Thanks!

**Comment by ollimenzel** [comment]
As far as I know it's because of conditional access settings. At least in our environment I'm not allowed to download Files from a private device. 
Why it's also not working on my company iPhone I'm not sure, but I assume it's not completely right set-up

**Comment by aprildunnam** [comment]
AS others have mentioned, there are sometimes conditional access policies that restrict getting images from SharePoint. In those cases the best path forward is to use Azure Blob Storage
