### ISSUE TITLE
Unable to Deploy the Solution - Hot Desk

### ISSUE THREAD

**Issue by tejasthite** [aprildunnam/PowerApps#39]
![image](https://user-images.githubusercontent.com/38923482/133094450-3d6dc927-7afb-492b-a312-d9a6ee5c8b7c.png)
 This is what i get when i try to deploy the solution? Any help please

**Comment by NobodyParticular** [comment]
Instead of importing at flow.microsoft.com as described in the install instructions, import it as a canvas app at make.powerapps.com > click "Solutions" in the left nav pane > Click the Import button at the top. Then just follow the prompts to complete the import and launch the app.
