### ISSUE TITLE
Times

### ISSUE THREAD

**Issue by barne77** [aprildunnam/PowerApps#4]
If I book Desk 1 for 9am until 11am and then try and book a 10am until 5pm if still offers me Desk 1

if I select 9am it doesn't, I think there is an issue with the gallery filter

can you help?

**Comment by barne77** [comment]
Filter(Desks,Not(Title in Filter(
    'Desk Reservations',
    startTime>=Min(CheckOutFrom,CheckOutTo) && startTime<=Max(CheckOutFrom,CheckOutTo) ||
    endTime>=Min(CheckOutFrom,CheckOutTo) && endTime<=Max(CheckOutFrom,CheckOutTo)
    ).DeskText))

**Comment by Z4YA** [comment]
> Filter(Desks,Not(Title in Filter(
> 'Desk Reservations',
> startTime>=Min(CheckOutFrom,CheckOutTo) && startTime<=Max(CheckOutFrom,CheckOutTo) ||
> endTime>=Min(CheckOutFrom,CheckOutTo) && endTime<=Max(CheckOutFrom,CheckOutTo)
> ).DeskText))

Thanks for this but I've noticed that it's not accurate either.
For example when you book 9am to 10am on desk 1 and then you try book for 10am to 11am on desk 1, it will not be available.

**Comment by GGILLET** [comment]
Hi @aprildunnam ; 

For this function : 

----------------------------
```
Filter(Desk_DSI;Not(Title in Filter(
    Desk_Reservations_DSI;
    startTime >= Min(CheckOutFrom;CheckOutTo) && startTime <= Max(CheckOutFrom;CheckOutTo) || endTime >= Min(CheckOutFrom;CheckOutTo) && endTime <= Max(CheckOutFrom;CheckOutTo) ||
    startTime <= Min(CheckOutFrom;CheckOutTo) && startTime <= Max(CheckOutFrom;CheckOutTo) || endTime <= Min(CheckOutFrom;CheckOutTo) && endTime >= Max(CheckOutFrom;CheckOutTo)
    ).DeskText))
```
------------------------------

Desk 1 booked 9am to 11am

If  I Try : 

1. 9am to 10am : OK Desk 1 isn't available.
2. 9am to 12pm : OK Desk 1 isn't available.
3. 9am to 1pm : OK Desk 1 isn't available.
4. 8am to 9am : OK Desk 1 isn't available.
5. 8am to 10am : OK Desk 1 isn't available.
6. 8am to 11am : OK Desk 1 isn't available.
7. 8am to 12pm : OK Desk 1 isn't available.
8. **11am to 12pm : KO Desk 1 isn't available.**
9. 12pm to 1pm : OK Desk 1 is available.

Can you help me with this case (8)  please?

Guillaume

**Comment by GGILLET** [comment]
Solution :

Filter(
    Desk_DSI;
    Not(
        Title in Filter(
            Desk_Reservations_DSI;
            CheckOutFrom >= startTime && CheckOutTo <= endTime || CheckOutFrom <= endTime && CheckOutTo >= endTime
        ).DeskText
    ))
