### ISSUE TITLE
Don't see the V3 template itself

### ISSUE THREAD

**Issue by OumalherDjiboZakari** [aprildunnam/PowerApps#40]
Hi Thank you so much for this template. I am learning to use powerapps and have customized it a car reservation template. I am excited for V3 of your template but can't find it anywhere. am I looking in the wrong spot perhaps?

**Comment by khennessy74** [comment]
Its in the DeskReservation folder ;-)

![image](https://user-images.githubusercontent.com/90855840/133752083-891dfd37-001a-497d-b294-c15359e079cd.png)

**Comment by aprildunnam** [comment]
Hi @OumalherDjiboZakari, the solution is in the DeskReservation Folder as @khennessy74 pointed out.
