### ISSUE TITLE
Desk Reservation in Chronological Order

### ISSUE THREAD

**Issue by PowerAppsGC** [aprildunnam/PowerApps#42]
Hi April,
We have deployed and are using the app and its working great. One thing people are asking for is that the desks are listed in chronological order of their booking and not in the order that they have booked.  For example if i book 3 desks.  31 Dec, 17 Nov, 9th Dec i would like to see them in the Dashboard as 17t Nov, 9th Dec, 31 Dec and not the previous.
i have been looking at the sort and from what i can tell it should be
FirstN(
    SortByColumns(
        Filter(
            'Desk Reservations',
            'Reserved By'.DisplayName = currentUser.FullName && 'Check Out From' >= Today()
        ),
        "CheckOutFrom",
        Descending
    ),
    3
)

Howerver the display is not showing what im wanting.  Can you advise what im missing from the sort?  Thanks in advance.

**Comment by aprildunnam** [comment]
This is the formula you would need for that:

FirstN(
    SortByColumns(
        Filter(
            'Desk Reservations',
            'Reserved By'.Email = currentUser.Email && 'Check Out From Number' >= Value(
                Text(
                    Today(),
                    "yyyymmddhmm"
                )
            )
        ),
        "CheckOutFromNumber",
       Descending
    ),
    2
)
