### ISSUE TITLE
Desk Reservation - Code did not work - No data

### ISSUE THREAD

**Issue by mnneumi** [aprildunnam/PowerApps#43]
Hello everyone,

thanks for sharing the file!

I have the issue, that the code did not work. I have created the Sharepoint-Lists exactly like the requirements (case sensitivity).
Do anyone know a solution for my problem? The syntax is not recognized.

Thank you! Kind regards
Michael

![image](https://user-images.githubusercontent.com/92186387/136626955-902b612e-1bf5-491f-a60d-8bee3af2ff41.png)

![image](https://user-images.githubusercontent.com/92186387/136627156-dc15acfc-4c45-450b-ada3-fadb6fd2f501.png)

**Comment by mnneumi** [comment]
@MyliuDideliBusta contact me lukamue7@gmail.com

**Comment by A-Jumper** [comment]
> Hello everyone,
> 
> thanks for sharing the file!
> 
> I have the issue, that the code did not work. I have created the Sharepoint-Lists exactly like the requirements (case sensitivity). Do anyone know a solution for my problem? The syntax is not recognized.
> 
> Thank you! Kind regards Michael
> 
> ![image](https://user-images.githubusercontent.com/92186387/136626955-902b612e-1bf5-491f-a60d-8bee3af2ff41.png)
> 
> ![image](https://user-images.githubusercontent.com/92186387/136627156-dc15acfc-4c45-450b-ada3-fadb6fd2f501.png)

Hello again, 

I ran into the issue you were experiencing here. I had to change mine to 'Check Out From Text', change the value to Today, and then I removed the text formatting line. Please note that I also changed the line for the 'Check Out From Text' line on the other though. 

The below worked for me:

```
FirstN(
    SortByColumns(
        Filter(
            'Desk Reservations',
            'Reserved By'.Email = currentUser.Email && 'Check Out From Text' >= Today()
        ),
        "CheckOutFromText",
        Ascending
    ),
    2
)
```


______


I had some additional sorting issues on some upcoming and previous pages I was working on from the original syntax and had to change my confirmation to the below:

```
ForAll(
    selectedDesks,
    Patch(
        'Desk Reservations',
        Defaults('Desk Reservations'),
        {
            Title: currentUser.FullName & " " & ThisRecord.Title,
            DeskText: ThisRecord.Title,
            'Check Out From': startTime,
            'Check Out From Text': DateAdd(startTime, TimeZoneOffset(), Minutes ),
            'Check Out From Number':Value(Text(startTime,"yyyymmddhmm")),
            'Check Out To': endTime, 
            'Check Out To Text': DateAdd(endTime, TimeZoneOffset(), Minutes ),
            'Check Out To Number': Value(Text(endTime,"yyyymmddhmm")),
            'Reserved By': {
                '@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedUser",
                Claims: "i:0#.f|membership|" & currentUser.Email,
                Department: "",
                DisplayName: currentUser.FullName,
                Email: currentUser.Email,
                JobTitle: "",
                Picture: ""
            }
        }
    )
);
Concurrent(
    Reset(ddTimeTo),
    Reset(ddTimeFrom),
    Reset(Calendar_1),
    Clear(selectedDesks),
    Set(
        selectedDate,
        Blank()
    ),
    Set(
        startTime,
        Today()
    ),
    Set(
        endTime,
        Today()
    )
);
Navigate(Success)
```

**Comment by subashp93** [comment]
HI 
I have a problem of connecting with SharePoint data list. can you help me ?

**Comment by sarah-nmachi** [comment]
@subashp93 what error are you getting while trying to connect?

![image](https://user-images.githubusercontent.com/45307720/148204703-c97af8c3-b275-4412-9d7f-eb1c4a042084.png)

**Comment by subashp93** [comment]
First I created Desk List 
![image](https://user-images.githubusercontent.com/91638695/148206994-60e4d65c-c24e-4e92-a274-c0d2bcadac13.png)
and again I created another list called Desk Reservations 
![image](https://user-images.githubusercontent.com/91638695/148207245-2abae950-e247-445b-90a4-b485a6a848d3.png)

and I have connected it with app  
![image](https://user-images.githubusercontent.com/91638695/148207370-45246573-8c24-41ba-8eff-60a9c11c01ce.png)

 but I dont see any connection between sharepoint data and app. how can I check it whether it is connected or not? 
when I tried to book a desk then I got this problem.
![image](https://user-images.githubusercontent.com/91638695/148207679-0fb2b292-c6c8-40aa-9552-1aaf240393c2.png)
  but there is some tables are available. so could you help me figure out my problem??

**Comment by sarah-nmachi** [comment]
@subashp93 Either you rename the Sharepoint list to "Desks" or you change your power app code to "Desks List"

![image](https://user-images.githubusercontent.com/45307720/148209421-89d51321-72c1-448e-ba1b-992f5d5ab441.png)
It should be "Desks" not "Desks List".

I hope this helps

**Comment by subashp93** [comment]
@sarah-nmachi  Yes now  I have changed it to Desks and seems like it is connected with app. but still I can not book a desk.
 I have following desk in Desks list
![image](https://user-images.githubusercontent.com/91638695/148214526-193f5812-7a8d-4488-a630-cf774de44fdc.png)
 but when I tried to book a desk then i got same problem.
![image](https://user-images.githubusercontent.com/91638695/148214626-5c9b5535-0e17-437a-a78c-e450516b3160.png)
what might be the reason of it??

**Comment by sarah-nmachi** [comment]
@subashp93 can you send me an email at sarahnmachi@gmail.com so we can have a teams or google meeting?

Or if you are not comfortable, we can continue here.

Check if you have an error on your powerapps, 

![image](https://user-images.githubusercontent.com/45307720/148225487-46355e1a-7300-4603-92b1-bc989062c25e.png)
if yes what is the error?

**Comment by subashp93** [comment]
@sarah-nmachi  
actually there is no error now. It works fine in power studio but when I publish it on web then I can not  see desk. what might be reason of it?

**Comment by sarah-nmachi** [comment]
> 
If it works pre-live, it should work after you publish it. I do not have more information, I may not be of help since there is no error message  or further information to troubleshoot

**Comment by AndriesJ86** [comment]
Hello @sarah-nmachi I have the same issue as described by the topic starter:

![image](https://user-images.githubusercontent.com/59652699/149529122-47fe66bc-675f-4aa6-a765-faf3b9e7d164.png)

I tried changing the semi-colon to a comma but that did throw other errors:

![image](https://user-images.githubusercontent.com/59652699/149529461-a3925392-8ec3-47b5-b4dd-b640095230a0.png)

Any help would be greatly appreciated! Thanks in advance!

@aprildunnam since multiple users seem to have problems with the code, what is your opinion on this?

**Comment by Danish-Izani** [comment]
Hello, can someone help me on how to connect the desk and desk reservation Sharepoint on this template?
I really appreciate it for someone to explain to me via Teams!
Thank you.

**Comment by Danish-Izani** [comment]
@sarah-nmachi sorry to ask you but I would really appreciate you to help me.

**Comment by Danish-Izani** [comment]
@sarah-nmachi thank you for the help but seems like I cannot make the desk appear as April did.

![image](https://user-images.githubusercontent.com/74799085/153043030-5a09c9b9-8d40-483f-9bd8-81394b1c42d3.png)

I have already made a new SharePoint as required. If you have a link for April's youtube video that guides on how to connect the SharePoint to the powerapps for this template, I really appreciate it!

**Comment by Danish-Izani** [comment]
@subashp93 I have the same problem with you on connecting with SharePoint data list.

I have already made the Sharepoint with the name Desk and Desk Reservations.

Do I need to insert something from this and connect the sahrepoint?

![image](https://user-images.githubusercontent.com/74799085/153048735-c5cbf276-3ab4-40fe-8359-16fd22cde36a.png)

**Comment by A-Jumper** [comment]
@Danish-Izani April has a section at the bottom of the template page called  - [Minimal Path to Awesome](https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation). Even though it looks like you have your lists connected, they are probably the sample connections. You need to remove them and then reconnect to your lists. The instructions in Minimal Path to Awesome will help you with that. If you change something in your lists, you may also need to go to the data section from time to time to refresh the connection to reflect the changes.

You need to ensure if you are using the template that every title/type/name matches up as she documented. There are two different versions of the template as well. 

Please note: If you publish the app and give a user/a group access to the app and they don't have access to read/write to the lists then they will not be able to see/edit anything.

**Comment by Danish-Izani** [comment]
@A-Jumper I already follow the instruction on Minipal Path to Awesome where I delete the sample connections and make a new two version Sharepoint.

The problem I encounter just now is even though I connect the new Sharepoint, the list of desk does not appear but instead said no openings were found.

![image](https://user-images.githubusercontent.com/74799085/153056461-162137ad-85c9-486a-ba44-3fcd9f2a1167.png)

How can I solve this issue?

**Comment by A-Jumper** [comment]
@Danish-Izani Did you change the active on the Desks list for each desk to 1? If not, you will need to make the desks you wish active to be 1 and then you will need to refresh the connected list.

**Comment by Danish-Izani** [comment]
@A-Jumper yes, I already change the active to 1.

![image](https://user-images.githubusercontent.com/74799085/153059741-c344acce-5409-4c52-a70a-bbf210028ee5.png)

But still the list of desks doesn't appear on the power apps.

**Comment by A-Jumper** [comment]
@Danish-Izani I see you have already made style changes on your images. Could you have edited any of the code that would pull this data? You may want to look at the errors you are getting in the window there and see if anything is missing. You can also use the checker in the top right by the back button.

If you think you may have configured something, you may want to start from scratch and try and set up a new App from the Template and connect your data and try to get a working model before customizing.

**Comment by Danish-Izani** [comment]
> I am hoping someone in this forum might be able to provide some insight with some issues I am having with the app. They are similar to what others here are seeing. I have read the posts here and tried the suggestions and still the issues persist.
> 
> My current reservations are not appearing in either the dashboard or the "My Appointments" section. I believe my lists are connected and set up correctly because when I highlight 'Desk Reservations' the reservations appear: <img alt="Upcoming" width="757" src="https://user-images.githubusercontent.com/99203375/153232756-cdbdf3a6-a798-4e8a-9ab4-f54d86639aa8.PNG">
> 
> I can go through the steps while in the studio and with the exception of my existing appointments not showing up, I can select a date and time, I can select a desk, I get the confirmation and the success message and the reservation appears in my Desk Reservations list in SharePoint. Any ideas why the existing reservations do not appear.
> 
> The next odd thing is that if I run the app outside of the studio, I still do not see my existing appointments, I can select a date and time but no matter what date and time I select, I get the message that nothing is available. Any ideas why the app would behave differently outside of the studio?
> 
> I appreciate any insight you all might have.

@mauifan have you solved this issue? I encounter the same issue as you after I use my company's SharePoint. Before that, I connected with my own SharePoint account and it doesn't have a problem. 

If you, have solved the issues that you face, can you help me solve it cause it was urgent?

**Comment by mauifan** [comment]
@Danish-Izani , I did figure out my issue.  Instead of using .Email = currentUser.eEmail to pull up the O365 account, my organization uses .Email = Office365Users.MyProfileV2().  As soon as I changed that in the galMyReservationsPreview screen along with the galPast and galUpcoming sections of MyAppts , the data from my Desk Reservation list populated correctly.  Still not sure why the app runs OK in the studio but not outside of the studio.  I hope that helps.

**Comment by Danish-Izani** [comment]
@mauifan Can I know how did you figure out that your organization uses .Email = Office365Users.MyProfileV2().

**Comment by Danish-Izani** [comment]
@mauifan or did you put anything between the bracket on .MyprofileV2()

**Comment by mauifan** [comment]
@Danish-Izani, I had to put in a ticket with my organization's Office365 support team and they provided me with the info.  There is nothing inside of the brackets.  The line looks like this:

FirstN(SortByColumns(Filter('Desk Reservations','Reserved By' .Email = Office365Users.MyProfileV2().mail && 'Check Out From'>=Today()),"CheckOutFrom", Ascending),5)

**Comment by Danish-Izani** [comment]
@mauifan Thank you very much. I really appreciate your help!

**Comment by aprildunnam** [comment]
This issue should be resolved in the latest version of the app found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip
