### ISSUE TITLE
Desk Reservation Provisioner Flow

### ISSUE THREAD

**Issue by MyliuDideliBusta** [aprildunnam/PowerApps#44]
![image](https://user-images.githubusercontent.com/50921298/136803940-cc287079-241f-4015-b766-420dbca7379a.png)

Action 'Add_a_field_to_the_default_view' failed

**Comment by TubaTim** [comment]
Hi there,

On the most recent update April mentioned that there are some people who have issues with the flow. You set that part up manually by going to the "Data Sources" section of the Read Me and creating the two SharePoint Lists: "Desks" and "Desk Reservations".
