### ISSUE TITLE
Current Day occupation percentage and list of users

### ISSUE THREAD

**Issue by MyliuDideliBusta** [aprildunnam/PowerApps#45]
Hi, 
Whole idea is to have a Tab where you can check how many percent of Desks are occupied with a list of users who are Booked for Today, Tomorrow, etc. Or Yesterday. ( we had a issue that someone left a messy desk so users cant see who was there yesterday.)

**Comment by aprildunnam** [comment]
I feel like that level of information might be best to get either from the SharePoint list itself or via adding a Power BI dashboard to report off the data
