### ISSUE TITLE
Manage Desk visible to all users, and it should be visible to owners only.

### ISSUE THREAD

**Issue by MyliuDideliBusta** [aprildunnam/PowerApps#46]
Title says everything.

**Comment by aprildunnam** [comment]
I added the functionality to be able to show/hide the desk management screens to the app but you would have to add the code to filter it.  If you go to the footer tab widget Items property you'll see each item has a "Visible" property.  You would need to put in a formula there which checks to see if the current user is in your owners group and if so set the visibility to true.
