### ISSUE TITLE
Office map image not refreshing after changes

### ISSUE THREAD

**Issue by luvdogzz3** [aprildunnam/PowerApps#47]
Hello. I have a link to the office map image hosted on the same SharePoint site as my desk and reservation lists. I had to make some changes to the map, and the image is correct when you click the link directly from the desks list. The link to the image is correct inside of the app itself, but it is not displaying the newest version. I have even renamed the image with no luck. This is only happening when the app is added as a tab in Microsoft Teams. If you open the app in the browser, it is fine. I've removed and re-added the app tab several times. Any ideas?

**Comment by A-Jumper** [comment]
Have you published this version on the app you edited and made it Live? You can view it while editing and it works but when you load it into Teams it is pulling in the published version you made Live. 

Hope this helps 🤙

[](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/save-publish-app)

**Comment by A-Jumper** [comment]
Have you published this version on the app you edited and made it Live? You can view it while editing and it works but when you load it into Teams it is pulling in the published version you made Live. 

Hope this helps 🤙

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/save-publish-app

**Comment by luvdogzz3** [comment]
> Have you published this version on the app you edited and made it Live? You can view it while editing and it works but when you load it into Teams it is pulling in the published version you made Live.
> 
> Hope this helps 🤙

A-Jumper thanks for your response. Yes, it is the published, live version. Browser works fine, but the published app is not showing the map link, though the link is correct. Interestingly, I just tested it by changing the location of the office map to an externally accessible location, and it works. No need to even update and republish the app because the map link is tied to the SharePoint list, which automatically updates in the app.

**Comment by A-Jumper** [comment]
> > Have you published this version on the app you edited and made it Live? You can view it while editing and it works but when you load it into Teams it is pulling in the published version you made Live.
> > Hope this helps 🤙
> 
> A-Jumper thanks for your response. Yes, it is the published, live version. Browser works fine, but the published app is not showing the map link, though the link is correct. Interestingly, I just tested it by changing the location of the office map to an externally accessible location, and it works. No need to even update and republish the app because the map link is tied to the SharePoint list, which automatically updates in the app.

Ahhh gotcha. Looks like this might just be a Teams issue. Have you tried clearing the Teams cache manually?

**Comment by luvdogzz3** [comment]
A-Jumper, the more I test, the more I believe the issue might lie with our internal security settings related to SharePoint. I have changed the link to the map within the SharePoint list to an external source and now it works, no update to the app is necessary. Thanks for the suggestion on clearing the Teams cache as well, totally forgot about that.

**Comment by A-Jumper** [comment]
> A-Jumper, the more I test, the more I believe the issue might lie with our internal security settings related to SharePoint. I have changed the link to the map within the SharePoint list to an external source and now it works, no update to the app is necessary. Thanks for the suggestion on clearing the Teams cache as well, totally forgot about that.

I was actually starting to experience a similar issue after my initial message...found out it was the SharePoint link for mine. Found earlier mentions of the issue. Only works if it is the full path and not the shared link. Needs to be like this: https://yoursharepointsite.sharepoint.com/sites/yoursite/yourlibrary/image.png

**Comment by A-Jumper** [comment]
> > A-Jumper, the more I test, the more I believe the issue might lie with our internal security settings related to SharePoint. I have changed the link to the map within the SharePoint list to an external source and now it works, no update to the app is necessary. Thanks for the suggestion on clearing the Teams cache as well, totally forgot about that.
> 
> I was actually starting to experience a similar issue after my initial message...found out it was the SharePoint link for mine. Found earlier mentions of the issue. Only works if it is the full path and not the shared link. Needs to be like this: https://yoursharepointsite.sharepoint.com/sites/yoursite/yourlibrary/image.png

Mine is still broken on some images but I did see other commenters mention converting the images to Base64string. Let me know if you found something that worked for you.

**Comment by aprildunnam** [comment]
These images related issues should be fixed with the latest update.  Power Apps now supports the native image field https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation
