### ISSUE TITLE
Additional Resources wont show in Training Portal

### ISSUE THREAD

**Issue by EmmaBens** [aprildunnam/PowerApps#48]
Hi, Im having problems getting the additional resources to show in the training portal. Ive added them in but the formula seems to be looking for something I dont understand;

Filter('Training Assets_1',Training_x0020_ID = Text(selectedCourse.ID))

any help would be appreciated.

**Comment by aprildunnam** [comment]
You have to make sure that in your Training Assets Document Library you have a Single Line of Text field called Training ID and that you map that to the ID of the Training Item's ID.
