### ISSUE TITLE
SharePoint lists - premission error

### ISSUE THREAD

**Issue by traconis** [aprildunnam/PowerApps#49]
Hi April,

I have changed SharePoint groups permission levels and the app stopped working (no permission to save into a Desk Reservation list).
I have reverted the permission, refreshed connections in the app but the booking is still broken. The app health checker and users trying the app all getting the same error: 
The requested operation is invalid. Server Response: Desk Reservation failed: The specified clientRequestId: xxxxxxxxx rtc.

![image](https://user-images.githubusercontent.com/862010/144600921-fac742ec-c3f8-4674-a788-2d0b36126c46.png)

**Comment by A-Jumper** [comment]
Hey @traconis not sure if you have already figured this out but if you haven't...did you grant the group access to edit the Desk Reservations list? If they can't edit the list, then they can't write that reservation to the list on the confirm page.

**Comment by aprildunnam** [comment]
+1 for what @A-Jumper suggested. If anything permissions wise has changed you have to make sure that anyone accessing the Power App has access to the underlying SharePoint lists.Another thing to try would be to remove and re-add the connections in the Power App

**Comment by traconis** [comment]
> Hey @traconis not sure if you have already figured this out but if you haven't...did you grant the group access to edit the Desk Reservations list? If they can't edit the list, then they can't write that reservation to the list on the confirm page.

Thanks for the tip. Unfortunatelly this was the first thing I checked.
After the long battle with Microsoft, rewriting entire part of the app (including removing data sources and re-adding them ) fixed the issue. :) . Sorry @aprildunnam , this turned out to be one of the Power Platform/Infrastructure common issues. Ie currently one user out of 1000 see dates in the US format despite network/SharePoint/PowerApps/PowerPlatform and the MMD (Microsoft Managed Device) regional settings are all as UK :D. But this is a story for a different topic.
