### ISSUE TITLE
Timesheet V2 actions controls are not working

### ISSUE THREAD

**Issue by NC1979** [aprildunnam/PowerApps#5]
Hi April,

In Timesheet V2 buttons like Save, Send for Approval, My Timesheet & Approval tab is not working.
Data is not getting stored in TimeEntries list.

**Comment by Mattross19** [comment]
I'm also having a similar issue. The lists were created after running the flow, but when I try to run Power Apps and input data, nothing appears on the TimeEntries list. 

Any help would be greatly appreciated.

**Comment by aprildunnam** [comment]
Please make sure you're using the most recent version of the app stored here: https://github.com/pnp/powerapps-samples/tree/main/samples/Timesheet
