### ISSUE TITLE
Time Away app

### ISSUE THREAD

**Issue by IamNivek** [aprildunnam/PowerApps#50]
I have tried for hours to get this working.  I have deleted the lists and recreated them multiple times exactly as it states in the ReadMe, but the app does not work.  I have changed the data sources and followed the instructions exactly, but there are errors everywhere.  Is this supposed to be a working app or is there more to it that I am missing.

Keep in mind, I am very new to PowerApps, so I'm sure it's just me!

![image](https://user-images.githubusercontent.com/96189618/146205158-bd61af8f-4288-48c9-9591-a678564c4d16.png)

"data:image/svg+xml," & EncodeUrl(
    "<svg width='100%' height='100%' viewBox='0 0 42 42' class='donut' xmlns='http://www.w3.org/2000/svg'>
  <circle class='donut-hole' cx='21' cy='21' r='15.91549430918954' fill='#ffffff'></circle>
  <circle class='donut-ring' cx='21' cy='21' r='15.91549430918954' fill='transparent' stroke='#ce4b99' stroke-width='3'></circle>
  <circle class='donut-segment' cx='21' cy='21' r='15.91549430918954' fill='transparent' stroke='#d2d3d4' stroke-width='3' stroke-dasharray='" & ThisItem.RequestedTimeOff / ThisItem.'TimeOffType:Allotted Time'.Value * 100 & " " & (100 - ThisItem.RequestedTimeOff / ThisItem.'TimeOffType:Allotted Time'.Value*100) & "' stroke-dashoffset='25'></circle>
</svg>"
)

**Comment by IamNivek** [comment]
OK, I think I have managed to fix some of the formulas, but this one is still giving me problems:

![image](https://user-images.githubusercontent.com/96189618/146271465-675ac098-441e-477c-a690-076a22254559.png)

I am not sure why it's saying it is division by 0 as I have >0 values in all my allotted time entries on the SPL.

**Comment by Tamara-Tarhe** [comment]
Hi, Please could you share how you resolved the division by zero error.

Thanks

**Comment by IamNivek** [comment]
> Hi, Please could you share how you resolved the division by zero error.
> 
> Thanks

I never did.  Gave up and created my own app.  It does not use the SVGs as I couldn’t never get it to work.  Started from scratch.

**Comment by DomVizor** [comment]
Do you have a project up as I'm having the same issues, declined days are being deducted and the zero error persists. Any help would be great :)

**Comment by ThomasMichelsen** [comment]
Hi @aprildunnam,

First of all thanks for a super App!

In the comments at Youtube you refer to Git hub for 1:1 comments to issues. I hoped to find a solution to this exact problem. Using commnets I have managed to solve all problemes except this one where there is an error regarding division by zero. I have the following in my image function, which I think looks right.. or am I wromg. Please advice me, so I can fix this.

`"data:image/svg+xml," & EncodeUrl(
    "<svg width='100%' height='100%' viewBox='0 0 42 42' class='donut' xmlns='http://www.w3.org/2000/svg'>
  <circle class='donut-hole' cx='21' cy='21' r='15.91549430918954' fill='#fff'></circle>
  <circle class='donut-ring' cx='21' cy='21' r='15.91549430918954' fill='transparent' stroke='#ce4b99' stroke-width='3'></circle>
  <circle class='donut-segment' cx='21' cy='21' r='15.91549430918954' fill='transparent' stroke='#d2d3d4' stroke-width='3' stroke-dasharray='" & ThisItem.RequestedTimeOff / ThisItem.'Allotted Time Off' * 100 & " " & (100 - ThisItem.RequestedTimeOff / ThisItem.'Allotted Time Off'*100) & "' stroke-dashoffset='25'></circle>
</svg>"
)`

Best regards,
Thomas
