### ISSUE TITLE
Unable to add additional rows in timesheet v2

### ISSUE THREAD

**Issue by rizviae99** [aprildunnam/PowerApps#53]
Went through the provisioning process, but got about 50+ errors

  The type of this argument 'BillTo' does not match the expected type 'ObjNull'. Found type 'Record'. For adding timesheet entries

**Comment by jaxkookie** [comment]
were you able to resolve this? Once imported you will need to delete the SharePoint list and add your that have been created?

**Comment by aprildunnam** [comment]
Please make sure you're using the latest version of this app and following the instructions in the ReadMe to manually create the underlying SharePoint list: https://github.com/pnp/powerapps-samples/tree/main/samples/Timesheet
