### ISSUE TITLE
Has something changed in powerapps that would cause time calculations to be off - Timesheet v2

### ISSUE THREAD

**Issue by jaxkookie** [aprildunnam/PowerApps#55]
@aprildunnam 
This morning all apps, including the original Timesheet v2 current Monday and weeklists dates are way off. just curious if I am the only one seeing this or if something has changed with powerapps?

**Comment by schittuluri1** [comment]
February issue with the timesheet app. The global variable is failing for February. I am trying to fix it by adding condition for Feb.
Set(
        weeksList,
        ForAll(
            Sequence(
                20,
                Day(
                    DateAdd(
                        Today(),
                        -1 * (Weekday(
                            Today(),
                            Monday
                        ) - 1),
                        Days
                    )
                ) - 28,
                7
            ),
            Date(
                Year(Today()),
                Month(Today()),
                Value
            )
        )
    )
    
![image](https://user-images.githubusercontent.com/34896174/152010741-dc468c53-ccd9-47fd-88e3-3b4bbe74bdb6.png)

**Comment by schittuluri1** [comment]
Here is the fix. Only for Feb change the number to 31.
If(Month(Today())=2,Set(
        weeksList,
        ForAll(
            Sequence(
                20,
                Day(
                    DateAdd(
                        Today(),
                        -1 * (Weekday(
                            Today(),
                            Monday
                        ) - 1),
                        Days
                    )
                ) - 31,
                7
            ),
            Date(
                Year(Today()),
                Month(Today()),
                Value
            )
        )
    ),Set(
        weeksList,
        ForAll(
            Sequence(
                20,
                Day(
                    DateAdd(
                        Today(),
                        -1 * (Weekday(
                            Today(),
                            Monday
                        ) - 1),
                        Days
                    )
                ) - 28,
                7
            ),
            Date(
                Year(Today()),
                Month(Today()),
                Value
            )
        )
    ))

**Comment by jaxkookie** [comment]
@schittuluri1 
very nice! I did find another solution that I did not love. So with a tweak to yours, I can get the previous few weeks and shorten the code.
`If(
    Month(Today()) = 2,
    Set(
        varM,
        31
    ),
    Set(
        varM,
        28
    )
);
Set(
            weeksList,
            ForAll(
                Sequence(
                    28,
                    Day(
                        DateAdd(
                            Today(),
                            -1 * (Weekday(
                                Today() - 45, // 5.5 weeks back
                                Monday
                            ) - 1),
                            Days
                        )
                    ) - varM, 
                    7
                ),
                Date(
                    Year(Today()),
                    Month(Today()),
                    Value
                )
            )
        )
    )
`

thanks again
