### ISSUE TITLE
Desk Reservation app - Asset not showing despite being available

### ISSUE THREAD

**Issue by Paolo750** [aprildunnam/PowerApps#57]
Hi April,
Last year I adapted your Desk Reservation app to use for our Pool car booking system (we currently only have 1 car and 1 van) and it has been working great until recently when a user reported that the car wasn't showing as available despite it not being booked out. 

I've been looking in to this and it appears to be related to where the app records the date as a number and uses this for filtering.  Below is a screen shot of the current entry that appears to be causing the issue.

If I change the 'Check out from Number' value to 1st Feb, 08:00 i.e. 10220220800 the car then shows as available again.
![Screenshot 2022-03-02 081925](https://user-images.githubusercontent.com/100757524/156322661-a5953ea6-df69-4a83-bb36-53f964ece9e6.png)

I'm unsure how to fix this, do you have any suggestions?

If I redevelop the app using CDS rather than SharePoint could I do the filtering on the actual check out from and too date fields without needing to record the date/time as a number?

I appreciate any help you can offer.
Thanks,

Paolo

**Comment by aprildunnam** [comment]
Please try the latest version of the app which should resolve most issues: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip
