### ISSUE TITLE
Desk Booking App

### ISSUE THREAD

**Issue by jbeirnemko** [aprildunnam/PowerApps#58]
Hi, the app is perfect for our needs thank you. Just one small issue here, the app doesnt log the booking in the users outlook calendar. Any ideas how to resolve please? TY, Jo

**Comment by aprildunnam** [comment]
Hi,
That functionality isn't part of this template.  You can easily add that functionality by incorporating a flow which sends the invite when the booking is made.  I show how to send an ICS calendar invite with Power Automate in this article:

https://powerusers.microsoft.com/t5/Power-Automate-Cookbook/ICS-Calendar-Invite/td-p/406036
