### ISSUE TITLE
Invalid Column Title for Desk Reservation Provisioner

### ISSUE THREAD

**Issue by cyberpau** [aprildunnam/PowerApps#6]
I tried to run the flow but I got this error:

![image](https://user-images.githubusercontent.com/21239062/96893467-4db4c880-14bd-11eb-9438-1df303c32ddd.png)

It seems that the column name doesn't match the names in the flow for the following texts:

- [ ] CheckOutFrom

- [ ] CheckOutTo

- [ ] ReservedBy

I have fixed the problem by editing the flow and addting space to the Titles, like this:

- [ ] Check Out From

- [ ] Check Out To

- [ ] Reserved By

We can do it this way, or the other way around.... 

If we use this way, we need to modify the canvas to replaces blank space with `_x0020_` e.g. `Check_x0020_Out_x0020_To`

If we modify the flow to remove the blank spaces, there's no need to edit the canvas

**Comment by aprildunnam** [comment]
Please try the latest version of the app which should resolve most issues: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip

This version has you manually create the SP list. Most issues are due to spaces in column names
