### ISSUE TITLE
Hello, tanks for your Apps , its cool

### ISSUE THREAD

**Issue by AlexisBellegueulle** [aprildunnam/PowerApps#61]
Hello , 1 Question if you have a time .
How to manage Hyperlink ( Map ) on your apps and Sharepoint List , i have try to add googlemap link on the SP , but not working .
Possible with simple Drawing Plan ?

Thanks in advance 

Kr
//Alex

**Comment by AutoEng2** [comment]
What you need to do is upload a file to Sharepoint (pdf or image file) and add a URL to the file for the map field.

**Comment by aprildunnam** [comment]
Power Apps now supports the native Image field in SharePoint which is the better way to handle this. I've updated the app to use the image field: https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation
