### ISSUE TITLE
DeskBooking MS App 

### ISSUE THREAD

**Issue by LS166638** [aprildunnam/PowerApps#62]
I found your awesome video for your Desk booking app. I tried to download the first folder (.msapp from the solution folder), but it doesn't seem to be active any longer. Is there somewhere else I can download this from?
https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation

**Comment by clayjam** [comment]
I also tried File -> Open on the .msapp file but received an error. Do you have an updated file that I can open/import ?
![image](https://user-images.githubusercontent.com/29591956/164131470-66926d6d-752f-4bca-946b-8b62607243a0.png)

**Comment by aprildunnam** [comment]
This issue should be resolved in the latest version of the app found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip


Please import this via the App tab in Power Apps and "Import app"
