### ISSUE TITLE
Deskbooking v3 duplicates

### ISSUE THREAD

**Issue by Landlord81** [aprildunnam/PowerApps#64]
Love your work and your videos, kudos to you.
I am looking for  way to prevent duplicate bookings within the powerapp.
Same space can be booked ontop of each other and with a limited space it is an issue.
Keep up the great work and hopefully something you have in mind!

**Comment by nicoride93** [comment]
In my team, we had the same issue. It is a time zone issue. The app saves the info in UTC and we are in CST, so at the time of comparing, the reservation times are not the same. 
Hope it helps!

**Comment by Landlord81** [comment]
Thanks for coming back, I had considered time zones, I have double checked the app and the attached sharepoint as well as my local sys admin settings it is all in UTC, Its a strange one tbh, I can replicate the issue on my own end as well but it's not consistent, I can book a desk and then try again and the desk doesn't show on the list, I can then try again and then book the same desk  in a refreshed session really has me stumped.

**Comment by Landlord81** [comment]
Just an update - I worked out my issue was related to non 365 users. Now that we have fully migrated the issue has resolved
