### ISSUE TITLE
Room Reservation

### ISSUE THREAD

**Issue by mrob22** [aprildunnam/PowerApps#67]
First and foremost, thank you for your product. This has helped in streamlining our room reservation process. 

I have an issue with room availbility filter when choosing selecting available rooms. For what ever reason, Filter( Rooms, Not( Title in Filter( 'Desks Reservations','Check Out From' >= startTime' && 'Check Out To' <= endTime || Check 'Check Out From' <= endTime && 'Check Out To' >= endTime ).RoomText ) && Active = 1 )
Is not removing rooms that are already booked for that time.

**Comment by asalinasmu** [comment]
This is great!  I also had the same issue.  It works for the specific user and they can't overbook themselves but where you see the issue is if you have two users with different sign ins, then it allows any other user to overbook an already booked timeframe.

**Comment by asalinasmu** [comment]
I also made sure I updated 'SelectedDesk' to whatever I want it to refer to instead, in my case 'SelectedDevices'.  She talks about it in this video at the 8:50 time mark.  Then I updated my formulas that then errored out to reflect that.  One of them being in the Confirm, btnConfirm, OnSelect formula and the patches that run in that area.

**Comment by aprildunnam** [comment]
Please try the latest version of the app which should resolve most issues: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip
