### ISSUE TITLE
SharePoint Element gets not deleted when reservation is in the past

### ISSUE THREAD

**Issue by HavidDartmann** [aprildunnam/PowerApps#69]
Hey!

Is there a way that I can automaticaly delete an entry when a reservation is in the past?

**Comment by AutoEng2** [comment]
You could create a flow for items older than yesterday's date.

**Comment by aprildunnam** [comment]
As AutoEng2 said, the best way to do this would be via a flow in Power Automate. I would create a "Scheduled" flow type that can run daily, use the SharePoint - Get Items action and filter it to return items where the end date is <= Today and then delete those items
