### ISSUE TITLE
Minimal Path to Awesome the download link goes to a 404

### ISSUE THREAD

**Issue by kolithagunarathne-pyxle** [aprildunnam/PowerApps#70]
Hi April,

The Minimal Path to Awesome, the download link goes to a page not found (404).  Can you fix this please.  The option that you have given is a bit confusing.

Thanks again.

**Comment by ianfraser-72** [comment]
hi - you can download directly from the source folder in the git repo

https://github.com/aprildunnam/PowerApps/tree/master/DeskReservation/solution

**Comment by aprildunnam** [comment]
Fixed. Thanks for reporting!
