### ISSUE TITLE
Error Power App

### ISSUE THREAD

**Issue by vivekthangaswamy** [aprildunnam/PowerApps#74]
![ErrorPowerApp](https://user-images.githubusercontent.com/4199464/184587512-c2663d58-0742-4a0c-a28d-a0f41fa5c161.JPG)

When I try to import the solution, I am facing the following error.

**Comment by AutoEng2** [comment]
Don't import the zip, just import the .msapp

**Comment by tblazeen** [comment]
Hello, I also experienced the same thing while trying to import DeskReservationListProvisioner_20200717134944

**Comment by tblazeen** [comment]
UPDATE:

I imported DeskReservationListProvisioner_20200717134944 using the "Import Canvass App" feature, and the flow was created.

![image](https://user-images.githubusercontent.com/16045296/185378498-a198ae52-925a-4073-ad59-19dc95abb08e.png)



![image](https://user-images.githubusercontent.com/16045296/185378213-dcabd1be-878b-43b6-89a3-63c8cfd42872.png)

**Comment by aprildunnam** [comment]
Please make sure you are using the latest version of the DeskReservation app which is found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip

This is a canvas app that you can import via the "Apps" tab and "Import App". You will manually create the lists and simply import the app
