### ISSUE TITLE
Desk Reservation Template

### ISSUE THREAD

**Issue by primadinh** [aprildunnam/PowerApps#75]
Hi

I just recently found you AMAZING template for the Desk Reservation app!  It is just what my company needs right now.  I was able to download the template and set up my list, but I am having some problems.   I am familiar with Power Apps but continuing to learn. 

When I test it, it appears to work but my desk selection screen does not appear and when I select the date to book it says "uh oh, no openings found!

I have watched all your videos and can't seem to bring in my Desk Select list to the screen.  Do you provide any step by step instruction on how to use this template correctly?

**Comment by eudy91** [comment]
Hi I am also facing this issue too. Hope to have the solution out soon.

**Comment by mattd699** [comment]
@primadinh @eudy91 i recently installed this too, i found that i had problems with the name of the SharePoint lists, make sure your lists are named:
Desk Reservations
Desks

Have you removed the data sources and added the lists back in as a data source?

Mines working overall but now very customised.

**Comment by citalex** [comment]
> 

This was my problem, thanks!
(had ' List' appended to the name of the lists)

**Comment by eudy91** [comment]
Hi, I did redo the list as per the instructions. But I still cannot get it to work. I am new to this. Any other suggestions?
Thank you all for the help and upcoming help.

**Comment by mattd699** [comment]
> Hi, I did redo the list as per the instructions. But I still cannot get it to work. I am new to this. Any other suggestions? Thank you all for the help and upcoming help.

Have you setup a Sharepoint site with the following lists:
Desk Reservations
Desks

April did put out a Powerflow which sets this up for you (List name and contents) but after running this you will need to rename the lists to match the above i stated.

You then need to edit the Powerapp and go to Data Sources, select Add data and use the Sharepoint option, find your site and the relevant lists as above.

If you need anymore help ill be able to reply lots today as I'm working on this application as im adding in a custom amount of days a desk can be booked and limitations such as an authorised users column so only managers can book certain desks etc.

**Comment by aprildunnam** [comment]
This issue should be resolved in the latest version of the app found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip

Other issues are likely due to inconsistencies in the list setup vs what the Power App is needing in the formulas

**Comment by Risenaj** [comment]
> 
Hello Mattd699
i am also very new and trying to teach myself on this app , i have added in all teh list and added in the columns. 
is there any data i need to populate in the list for it to show, up, i am just getting red crosses and error all over the app?

**Comment by mattd699** [comment]
> > 
> 
> Hello Mattd699 i am also very new and trying to teach myself on this app , i have added in all teh list and added in the columns. is there any data i need to populate in the list for it to show, up, i am just getting red crosses and error all over the app?

Did you used the latest version April posted above? 
see comment Dec 31, 2022

**Comment by Risenaj** [comment]
> > > 
> > 
> > 
> > Hello Mattd699 i am also very new and trying to teach myself on this app , i have added in all teh list and added in the columns. is there any data i need to populate in the list for it to show, up, i am just getting red crosses and error all over the app?
> 
> Did you used the latest version April posted above? see comment Dec 31, 2022

Hello Mattd699

I did use the new one that was posted from Jan this year , i found the Power automate provisioning.zip 
and have run it , is it supposed to create the lists with all the right columns? as it run when i switch the sharepoint site to point to a folder instead of just SharePoint site root that i created.

from the errors in Powerapps , all the red crosses show they cannot find the right columns even though i have created the list manually 

i have attached some screenshots so far 
![List1](https://user-images.githubusercontent.com/63654888/220910486-71bd95e7-ddb3-4099-9e4a-8245e00000cb.jpg)rror1.jpg…]()![Columns](https://user-images.githubusercontent.com/63654888/220910466-b036987d-31e2-41e8-a591-9a3f7fc23253.jpg)

**Comment by mattd699** [comment]
> ![Error1](https://user-images.githubusercontent.com/63654888/220910944-a30fc9f8-1656-4883-b50c-847fd7176c50.jpg)
> 
> > > > 
> > > 
> > > 
> > > Hello Mattd699 i am also very new and trying to teach myself on this app , i have added in all teh list and added in the columns. is there any data i need to populate in the list for it to show, up, i am just getting red crosses and error all over the app?
> > 
> > 
> > Did you used the latest version April posted above? see comment Dec 31, 2022
> 
> Hello Mattd699
> 
> I did use the new one that was posted from Jan this year , i found the Power automate provisioning.zip and have run it , is it supposed to create the lists with all the right columns? as it run when i switch the sharepoint site to point to a folder instead of just SharePoint site root that i created.
> 
> from the errors in Powerapps , all the red crosses show they cannot find the right columns even though i have created the list manually
> 
> i have attached some screenshots so far ![List1](https://user-images.githubusercontent.com/63654888/220910486-71bd95e7-ddb3-4099-9e4a-8245e00000cb.jpg)rror1.jpg…]()![Columns](https://user-images.githubusercontent.com/63654888/220910466-b036987d-31e2-41e8-a591-9a3f7fc23253.jpg)

I cant see the column in reference, can you expand it?

Within your application have you set the data sources so it match's your own SharePoint list?

**Comment by Risenaj** [comment]
> > ![Error1](https://user-images.githubusercontent.com/63654888/220910944-a30fc9f8-1656-4883-b50c-847fd7176c50.jpg)
> > > > > 
> > > > 
> > > > 
> > > > Hello Mattd699 i am also very new and trying to teach myself on this app , i have added in all teh list and added in the columns. is there any data i need to populate in the list for it to show, up, i am just getting red crosses and error all over the app?
> > > 
> > > 
> > > Did you used the latest version April posted above? see comment Dec 31, 2022
> > 
> > 
> > Hello Mattd699
> > I did use the new one that was posted from Jan this year , i found the Power automate provisioning.zip and have run it , is it supposed to create the lists with all the right columns? as it run when i switch the sharepoint site to point to a folder instead of just SharePoint site root that i created.
> > from the errors in Powerapps , all the red crosses show they cannot find the right columns even though i have created the list manually
> > i have attached some screenshots so far ![List1](https://user-images.githubusercontent.com/63654888/220910486-71bd95e7-ddb3-4099-9e4a-8245e00000cb.jpg)rror1.jpg…]()![Columns](https://user-images.githubusercontent.com/63654888/220910466-b036987d-31e2-41e8-a591-9a3f7fc23253.jpg)
> 
> I cant see the column in reference, can you expand it?
> 
> Within your application have you set the data sources so it match's your own SharePoint list?

Many thank for the promot reply 

which column would you like to see ?
i have removed the Data sources that came with the import and added in the three-list data sources.
it seems to be picking up the data sources but i keep getting a few errors where you cand find the columns but the column us there.

**Comment by Risenaj** [comment]
> Have you set the column as the correct data type? Its hard for me to help in V3 as i had V2 and added in a lot of changes and customisations

I totally get you, i reloaded all the data sources and it looks like its wokring alot better , on V2 how did you get the desk to show up , do i need to populate the desks list with data, like tell it how many desks i have.
and i see in two separate posts her if you look, for the MAP one says hyperlink , how would i add that and the other says map
  
https://github.com/aprildunnam/PowerApps/blob/4b5be30bc68475bba4a2b203562f841048b4d0aa/DeskReservation/README.md

https://github.com/jesusfer/DeskReservation

**Comment by RandriatahinaCharles** [comment]
Hi all,

I am trying to upload app and perform some customization. All work very well except the multiple select on calendar date. 
I can't select more than one date at the same time when I am trying to book a place.

 
<img width="205" alt="date select" src="https://github.com/aprildunnam/PowerApps/assets/165014430/e198bd38-888b-4c55-8c6f-4a2d36292082">

I see that on your screeshot on the select Date screen, multiple selection should be available. 
![Book select multiple](https://github.com/aprildunnam/PowerApps/assets/165014430/b4b14edf-56f2-4eba-b207-d380375354b4)

Could you tell me how to configure it to work ?

**Comment by Alcately** [comment]
I am having the same issue as  @RandriatahinaCharles here above mentions.
The app works but i cannot seem to select more than 1 date which is kinda crucial for me.

@RandriatahinaCharles Did you find a solution in the meantime please?
