### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by AdamCarterCloudCollective** [aprildunnam/PowerApps#8]
Hello, Thanks for the fab template of the booking app it will be a great help on a upcoming project. I am having flow issues though. It keeps timing out of the create desks list, all it says is bad gateway. I am very new to powerapps & especially flow :-(. i seem to have issues every time I use it. All help would be greatly appreciated . 
Thanks
Adam

**Comment by MyliuDideliBusta** [comment]
Same here, what was the solution
