### ISSUE TITLE
Not able to create new desk from power app

### ISSUE THREAD

**Issue by Ainzo92** [aprildunnam/PowerApps#82]
Hi April,

Thank you for your effort and time you put in this app.

I have an issue. When I create a new desk from powerapp and I click on update but it does not save anything in SharePoint. Because it is a Patch function to only update existing data.

2- When I book a desk from 14u-17u. I was able to double book the desk from 15u to 17u.

Thanks again.

**Comment by aprildunnam** [comment]
This issue should be resolved in the latest version of the app found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip
