### ISSUE TITLE
Overlapping booking with date range

### ISSUE THREAD

**Issue by albertocaa1317** [aprildunnam/PowerApps#83]
Hi,
there is a bug in the booking with date range.

I have a booking in a date range:
![image](https://user-images.githubusercontent.com/57954993/207870684-4f15c189-804c-4d20-a115-2f95fb3daf55.png)

If I try to create a new reservation with a date range with these conditions:
- the startdate is within another reserved date range. (i.e.: 19th, 20th Dec)
- the enddate is after the same date range as before (i.e.: 20th, 21th Dec)
![image](https://user-images.githubusercontent.com/57954993/207870710-52ef08b2-665f-485f-84a0-62f584b433cd.png)

The desk booked in the first date range is available! It should be hidden because in the new date range that I want to book there are days when this desk is booked.
![image](https://user-images.githubusercontent.com/57954993/207870735-381fc83f-3a09-48bc-8af1-5ff5f1e72ea3.png)

![image](https://user-images.githubusercontent.com/57954993/207870750-eb4898e5-60f5-476b-82b6-f1c8d6747798.png)

Finally I have a double booking to the Desk01 on the day 20th Dec
![image](https://user-images.githubusercontent.com/57954993/207870774-45c0e493-8a1a-406e-8165-1d0cee2577c5.png)

Does anyone can help me to fix this?

Thanks.

**Comment by lemming303** [comment]
Hi,
I had this issue a while back, but I don't remember where I found this fix. 
Change the filter for the available desks (In Page "DeskSelect" -> "galleryAvailDesk" -> Item-Property) to this:

`Filter(
	Desks;
		Not(
		Title in Filter(
			'Desk Reservations';
			'Check Out To' >= DateAdd(startTime; 1; Minutes ) && 'Check Out To' <= endTime || 'Check Out From' <= endTime && 'Check Out To' >= endTime
		).DeskText
	) && Active = 1
)`

Your SharePoint List Column names might be different, in the template it's CheckOutFrom and CheckOutTo, in my case it's "Check Out From".

**Comment by aprildunnam** [comment]
This issue should be resolved in the latest version of the app found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip
