### ISSUE TITLE
TimeSheet Provisioner

### ISSUE THREAD

**Issue by VictorMoquist** [aprildunnam/PowerApps#9]
Dear April,

I get the following error message when I try to import the TimeSheet provisioner in Flows. Not sure whether I am importing it correctly?
"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported."

**Comment by sanjaysy** [comment]
Hello April,

I'm also getting the same error.
can you please help us.

Regards,
Sanjay

**Comment by ITAHIR1982** [comment]
any update? I am getting the same error.

**Comment by TUXEDOCAT7** [comment]
FYI - I was getting the same error and I went back to the YouTube video.  April posted a reply to someone's comment and I realized I was making the same mistake.  I was trying to import the zip file under Solutions in the left nav.  But you need to go to Power Apps --> Apps and then look for the "Import Canvas App" at the top of the page next to "New App" and import the Power App zip.  Same thing for Power Automate -->My Flows and look for "Import" at the top of the page next to "New Flow" and import the Power Automate zip.  Hope this helps.
**[Here is April's response:](https://www.youtube.com/watch?v=zroxwXpVhHI)**  
April Dunnam
3 months ago
Hi Bader - If you look on the instructions on Github you'll see that this isn't a solution file.  What's provided is an export of a Canvas app and another export of a Flow.  So you'll need to import via the "Import App" button in Power Apps and "Import Flow" button in Power Automate for it to work, NOT the solutions tab.

**Comment by aprildunnam** [comment]
Closing this out as @TUXEDOCAT7 posted the solution:

If you look on the instructions on Github you'll see that this isn't a solution file. What's provided is an export of a Canvas app and another export of a Flow. So you'll need to import via the "Import App" button in Power Apps and "Import Flow" button in Power Automate for it to work, NOT the solutions tab.

**Comment by pen1064** [comment]
Hi I have encountered error in creating the list file, it seems like my school does not give me permssion on that. Do you mind to share the schema of the list?
